/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "Buffer messages in seconds to avoid system overload": {"en": "Buffer messages in seconds to avoid system overload", "de": "Puffern Sie Nachrichten in Sekundenschnelle, um eine Systemüberlastung zu vermeiden", "ru": "Буферизация сообщений за считанные секунды, чтобы избежать перегрузки системы.", "pt": "Mensagens de buffer em segundos para evitar sobrecarga do sistema", "nl": "Buffer berichten binnen enkele seconden om systeemoverbelasting te voorkomen", "fr": "Tamponnez les messages en quelques secondes pour éviter la surcharge du système", "it": "Buffer dei messaggi in pochi secondi per evitare il sovraccarico del sistema", "es": "Almacene los mensajes en segundos para evitar la sobrecarga del sistema", "pl": "Buforuj wiadomości w ciągu kilku sekund, aby uniknąć przeciążenia systemu", "zh-cn": "在几秒钟内缓冲消息以避免系统过载"},
    "Leave empty or 0 to not expire states": {       "en": "Leave empty or 0 to not expire states",           "de": "Leer lassen oder 0, um den Status nicht abzulaufen", "ru": "Оставьте пустым или 0, чтобы состояния не истекали.", "pt": "Deixe em branco ou 0 para não expirar os estados", "nl": "Laat leeg of 0 om de status niet te laten verlopen", "fr": "Laissez vide ou 0 pour ne pas expirer les états", "it": "Lascia vuoto o 0 per non far scadere gli stati",  "es": "Déjelo vacío o 0 para que no caduquen los estados", "pl": "Pozostaw puste lub 0, aby stany nie wygasały",    "zh-cn": "留空或 0 表示不过期状态"},
    "Please choose your preferred settings": {       "en": "Please choose your preferred settings",           "de": "Bitte wählen Sie Ihre bevorzugten Einstellungen", "ru": "Пожалуйста, выберите предпочитаемые настройки",   "pt": "Escolha suas configurações preferidas",           "nl": "Kies uw voorkeursinstellingen",                   "fr": "Veuillez choisir vos paramètres préférés",        "it": "Scegli le impostazioni preferite",                "es": "Por favor elige tu configuración preferida",      "pl": "Wybierz preferowane ustawienia",                  "zh-cn": "请选择您喜欢的设置"},
    "USBDevice": {                                   "en": "USB device Port",                                 "de": "USB-Geräteanschluss",                             "ru": "Порт USB-устройства",                             "pt": "Porta do dispositivo USB",                        "nl": "USB-apparaatpoort",                               "fr": "Port de périphérique USB",                        "it": "Porta del dispositivo USB",                       "es": "Puerto del dispositivo USB",                      "pl": "Port urządzenia USB",                             "zh-cn": "USB设备端口"},
    "device1Path": {                                 "en": "Device 1 path",                                   "de": "Pfad Gerät 1",                                    "ru": "Путь устройства 1",                               "pt": "Caminho do dispositivo 1",                        "nl": "Pad apparaat 1",                                  "fr": "Chemin appareil 1",                               "it": "Percorso dispositivo 1",                          "es": "Ruta del dispositivo 1",                          "pl": "Ścieżka urządzenia 1",                            "zh-cn": "设备1路径"},
    "device2Path": {                                 "en": "Device 2 path (optional)",                        "de": "Pfad Gerät 2 (optional)",                         "ru": "Путь устройства 2 (необязательно)",               "pt": "Caminho do dispositivo 2 (opcional)",             "nl": "Pad apparaat 2 (optioneel)",                      "fr": "Chemin appareil 2 (optionnel)",                   "it": "Percorso dispositivo 2 (opzionale)",              "es": "Ruta del dispositivo 2 (opcional)",               "pl": "Ścieżka urządzenia 2 (opcjonalnie)",              "zh-cn": "设备2路径（可选）"},
    "device3Path": {                                 "en": "Device 3 path (optional)",                        "de": "Pfad Gerät 3 (optional)",                         "ru": "Путь устройства 3 (необязательно)",               "pt": "Caminho do dispositivo 3 (opcional)",             "nl": "Pad apparaat 3 (optioneel)",                      "fr": "Chemin appareil 3 (optionnel)",                   "it": "Percorso dispositivo 3 (opzionale)",              "es": "Ruta del dispositivo 3 (opcional)",               "pl": "Ścieżka urządzenia 3 (opcjonalnie)",              "zh-cn": "设备3路径（可选）"},
    "expireTime": {                                  "en": "Expiration time of states in seconds",            "de": "Ablaufzeit der Zustände in Sekunden",             "ru": "Время истечения состояний в секундах",            "pt": "Tempo de expiração dos estados em segundos",      "nl": "Vervaltijd van staten in seconden",               "fr": "Temps d'expiration des états en secondes",        "it": "Tempo di scadenza degli stati in secondi",        "es": "Tiempo de vencimiento de los estados en segundos.", "pl": "Czas ważności stanów w sekundach",                "zh-cn": "状态的过期时间（以秒为单位）"},
    "fastStateInterval": {                           "en": "Fast states write window (seconds)",              "de": "Schreibfenster für schnelle States (Sekunden)",   "ru": "Окно записи быстрых состояний (секунды)",         "pt": "Janela de gravação para estados rápidos (segundos)", "nl": "Schrijfvenster voor snelle states (seconden)",   "fr": "Fenêtre d'écriture des états rapides (secondes)", "it": "Finestra di scrittura stati rapidi (secondi)",    "es": "Ventana de escritura de estados rápidos (segundos)", "pl": "Okno zapisu szybkich stanów (sekundy)",          "zh-cn": "快速状态写入窗口（秒）"},
    "normalStateInterval": {                         "en": "Normal states write window (seconds)",            "de": "Schreibfenster für normale States (Sekunden)",    "ru": "Окно записи обычных состояний (секунды)",         "pt": "Janela de gravação para estados normais (segundos)", "nl": "Schrijfvenster voor normale states (seconden)", "fr": "Fenêtre d'écriture des états normaux (secondes)", "it": "Finestra di scrittura stati normali (secondi)",   "es": "Ventana de escritura de estados normales (segundos)", "pl": "Okno zapisu normalnych stanów (sekundy)",       "zh-cn": "普通状态写入窗口（秒）"},
    "slowStateInterval": {                           "en": "Slow states write window (seconds)",              "de": "Schreibfenster für langsame States (Sekunden)",   "ru": "Окно записи медленных состояний (секунды)",       "pt": "Janela de gravação para estados lentos (segundos)", "nl": "Schrijfvenster voor trage states (seconden)",    "fr": "Fenêtre d'écriture des états lents (secondes)",   "it": "Finestra di scrittura stati lenti (secondi)",     "es": "Ventana de escritura de estados lentos (segundos)", "pl": "Okno zapisu wolnych stanów (sekundy)",          "zh-cn": "慢速状态写入窗口（秒）"},
    "messageBuffer": {                               "en": "Buffer in seconds to ignore messages",            "de": "Puffer in Sekunden, um Nachrichten zu ignorieren", "ru": "Буфер в секундах для игнорирования сообщений",    "pt": "Buffer em segundos para ignorar mensagens",       "nl": "Buffer in seconden om berichten te negeren",      "fr": "Tampon en quelques secondes pour ignorer les messages", "it": "Buffer in pochi secondi per ignorare i messaggi", "es": "Buffer en segundos para ignorar mensajes",        "pl": "Bufor w ciągu kilku sekund, aby ignorować wiadomości", "zh-cn": "以秒为单位进行缓冲以忽略消息"},
};
